var countries = [ 
  'Afghanistan', 
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'AndorrA',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia', 
  'Aruba',
  'Australia',
  'Austria', 
  'Azerbaijan',
  'Bahamas',
  'Bahrain', 
  'Bangladesh', 
  'Barbados', 
  'Belarus',
  'Belgium', 
  'Belize',
  'Benin', 
  'Bermuda',
  'Bhutan', 
  'Bolivia', 
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon', 
  'Canada',
  'Cape Verde',
  'Cayman Islands', 
  'Central African Republic',
  'Chad',
  'Chile',
  'China', 
  'Christmas Island', 
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo', 
  'Cook Islands',
  'Costa Rica',
  'Cote DIvoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark', 
  'Djibouti', 
  'Dominica', 
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador', 
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana', 
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man', 
  'Israel', 
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan', 
  'Kazakhstan', 
  'Kenya',
  'Kiribati',
  'Korea', 
  'Kuwait',
  'Kyrgyzstan',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia',
  'Madagascar', 
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal', 
  'Netherlands', 
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama', 
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar', 
  'Reunion',
  'Romania',
  'Russian Federation',
  'RWANDA',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands, British',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

var indian_cities = ['Agartala','Agra','Ahmedabad','Ahmednagar','Aizawa','Ajmer','Alappuzha','Aligarh','Allahabad','Almora','Ambala','Amritsar','Anand','Anantapur','Ankleshwar','Asansol','Aurangabad','Baddi','Bareilly','Bathinda','Belgaum','Bellary','Bangalore','Bhagalpur','Bharuch','Bhavnagar','Bhillai','Bhilwara','Bhopal','Bhubaneshwar','Bhuj','Bidar','Bilaspur','Bokaro','Chamoli','Chandigarh','Chennai','Coimbatore','Cuddalore','Cuttack','Dadra nagar haveli','Silvassa','Dalhousie','Daman and diu','Dehradun','Delhi','Dhanbad','Dharmasala','Dharwad','Dimapur','Durgapur','Kochi','Erode','Faizabad','Faridabad','Gandhinagar','Gangtok','Ghaziabad','Goa','Gorakhpur','Gulbarga','Guntakal','Guntur','Gurgaon','Guwahati','Gwalior','Haldia','Haldwani','Haridwar','Hisar','Hosur','Hubli','Hyderabad','Idukki','Imphal','Indore','Itanagar','Jabalpur','Jaipur','Jaisalmer','Jalandhar','Jalgaon','Jammu','Kashmir','Jamnagar','Jamshedpur','Jodhpur','Kakinada','Kandla','Kanpur','Karnal','Kasargode','Kharagpur','Kolar','Kolhapur','Kolkata','Kollam','Kota','Kottayam','Kozhikode','Kulu manali','Kurnool','Kurukshetra','Lakshadweep','Lucknow','Ludhiana','Madurai','Malappuram','Mangalore','Mathura','Meerut','Mohali','Moradabad','Mumbai','Mysore','Nagercoil','Nagpur','Nainital','Nasik','Navi mumbai','Ncr','Nellore','Nizamabad','Noida','Ooty','Palakkad','Panipat','Panaji','Paradeep','Pathanamthitta','Pathankot','Patiala','Patna','Pondicherry','Porbandar','Port blair','Pune','Puri','Raigarh','Raipur','Rajahmundry','Rajkot','Ranchi','Rishikesh','Rohtak','Roorkee','Rourkela','Rudraprayag','Rudrapur','Salem','Shillong','Shimla','Sikkim','Silchar','Siliguri','Solapur','Srinagar','Surat','Thanjavur','Thrissur','Tirunalveli','Tirupati','Trichy','Tripura','Trivandrum','Tuticorin','Udaipur','Ujjain','Uttarkashi','Vadodara','Valsad','Vapi','Varanasi','Vasco da gama','Vellore','Vijayawada','Visakhapatnam','Warangal','Wayanad'];